name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packages
      run: |
        export PYTHONIOENCODING=UTF8
        pip install coveralls pytest-cov ptyprocess

    - name: Run tests
      run: |
        ./tools/display-sighandlers.py
        ./tools/display-terminalinfo.py
        py.test --cov pexpect --cov-config .coveragerc

    - name: Check coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
